---

- name: Install Ansible required packages
  become: yes
  apt:
    name: "{{ item }}"
  with_items:
    - dpkg-dev
    - libffi-dev
    - libssl-dev
    - libyaml-cpp-dev
    - python2.7
    - python-dev
    - python-pip

- name: Install latest version of setuptools
  become: yes
  pip:
    name: setuptools
    state: latest

- name: Install Ansible
  become: yes
  pip:
    name: ansible
    version: "{{ ansible.version }}"
